services:
  mysql:
    container_name: mysql
    image: ${ZABBIX_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - "./zabbix/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  zabbix-server:
    container_name: zabbix-server
    image: ${ZABBIX_SERVER}
    links:
      - mysql
    restart: always
    ports:
      - 10051:10051
    volumes:
      - "./zabbix/alertscripts:/usr/lib/zabbix/alertscripts"
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

  zabbix-web:
    container_name: zabbix-web
    image: ${ZABBIX_WEB}
    links:
      - mysql
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PHP_TZ: ${PHP_TIMEZONE}
    depends_on:
      - mysql
      - zabbix-server

  grafana:
    container_name: grafana
    image: grafana/grafana
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: ${ZABBIX_AGENT}
    user: root
    links:
      - zabbix-server
    depends_on:
      - zabbix-server
    restart: always
    privileged: true
    ports:
      - 10050:10050
    volumes:
      - /var/run:/var/run
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
